### ISSUE TITLE
Conversion is Simply not Happening

### ISSUE THREAD

**Issue by Varun-Sharma-1981** [DouglasCAyers/sfdc-convert-notes-to-chatter-notes#15]
I'm trying to do a test convert and have also enabled the trigger. Neither is working for me at the moment. Please help!

**Comment by Varun-Sharma-1981** [comment]
This is the error I am getting in the logs:

Required fields are missing: [Expires_c]. I've realized that there is a custom field on the Content object with this name. How can we workaround this if we need to keep the field?

**Comment by douglascayers** [comment]
Hi @Varun-Sharma-1981,

Thanks for using my conversion tool. Hrm, custom required fields can be a problem for data migrations.

Here are some options to consider:

1. Remove the validation that makes the custom field `Expires__c` required
2. At the field level, specify a default value so no new ContentVersion records have this null
3. Introduce a `before insert` trigger on `ContentVersion` object to default the value
4. Rather than deploy the managed package of my conversion app, deploy the source code from GitHub then modify the `ConvertNotesToContentNotesService` apex class as needed

Thanks,

Doug
