### ISSUE TITLE
Been running process for days but now get Salesforce System error

### ISSUE THREAD

**Issue by MikeF2017** [DouglasCAyers/sfdc-convert-notes-to-chatter-notes#25]
Hi,

I have been using the Notes to Enhanced notes conversion app and been doing 2000 conversions in a 24 hour period including deleting the old note as it goes to the Enhanced notes.   Come the batch count left at 100 but it will no longer process.  I get the same issue in both Production and Testing sandbox(full). 

Error is : Salesforce System Error: 1439474981-49883 (123133497) (123133497)

It will no longer process any batches.  I have turned off delete and also sent a batch with 1 record and it takes a while to process and then shows this error.

Any help would be appreciated.  Trying to convert the notes by end of month or ASAP. 

Thanks

Mike

**Comment by douglascayers** [comment]
Hi Mike,

Glad that you’re finding use for this conversion app. 

That error (more info about it on project README page in FAQ section) means one or more notes contain invalid characters that don’t allow conversion to Enhanced Note. 

I’ve been round and round with Salesforce support and their engineers, and because Salesforce doesn’t log customers data their error messages won’t tell us what character failed to convert. Unfortunately they also won’t publish exhaustive list of unsupported characters. 

What most have found that works is reduce batch size to 1 and begin converting again and then try to identify the note that failed. Because that error fails completely my code has no chance to log any details about it. 

You would be looking for probably any non-ASCII printable characters. Fancy symbols. 

If you do identify the problematic characters please let me know so I can improve the conversion tool. 

I’m going to close this issue as there’s nothing I can really do here that I know of, it’s now a needle in the haystack kind of hunt on your end, sadly. 

Thanks

**Comment by douglascayers** [comment]
You may be interested in following this issue for if/when I’m able to add to add better intelligence to inspecting if Note contains invalid content: https://github.com/DouglasCAyers/sfdc-convert-notes-to-chatter-notes/issues/24

**Comment by MikeF2017** [comment]
Hi Doug, 

It was due to the non ascii codes. Just needed to update these.  In our data we had the diamond with question marks in it. Adjust ed this and now it is running again. 

Thanks 

Mike

**Comment by douglascayers** [comment]
Thanks for the confirmation @MikeF2017
