### ISSUE TITLE
Note Not Editable After Conversion

### ISSUE THREAD

**Issue by juicyroots** [DouglasCAyers/sfdc-convert-notes-to-chatter-notes#29]
I just created an old note, and used the tool to convert the single ID (Opportunity). It worked perfectly, but I just realized that I can now no longer edit the Enhanced Note. Did I miss something?

**Comment by douglascayers** [comment]
Hi @juicyroots, Enhanced Notes use a different sharing model than Classic Notes. My first guess is that perhaps the note that got converted is owned by a user other than you? Or, make sure you are in Lightning Experience then try to edit the converted note.

**Comment by douglascayers** [comment]
Hi @juicyroots,

Enhanced Notes default behavior is to grant only **view** access. In Lighting Experience, [by design](https://help.salesforce.com/articleView?id=notes_share_sfx.htm&type=5) the Enhanced Notes do not support multiple users editing the same record so they do not expose a way to grant **edit** access.

One [workaround](https://success.salesforce.com/answers?id=9063A000000pLIgQAM) is to use either Data Loader or an Apex trigger to modify the `ContentDocumentLink` records and set the `ContentDocumentLink.ShareType` field value to `C` (collaborator).

 The other workaround is to switch to **Classic**, view the note record detail page, click on **Note Sharing Settings** and assign users or groups to have collaborator access.
