### ISSUE TITLE
Batches are failing

### ISSUE THREAD

**Issue by danhowellnz** [DouglasCAyers/sfdc-convert-notes-to-chatter-notes#31]
Great tool. Saved me a lot of time with data migration.

It seems successfully process a 1-3 batches and then stop. I have tried batch size of 1 and it processed 4 records. Batch size of 5 and 10 records. There are no triggers or automations.

**Comment by danhowellnz** [comment]
I installed the code, the debug logs say "FATAL_ERROR Internal Salesforce.com Error" on the "SerialBatchApexRangeChunkHandler"

**Comment by danhowellnz** [comment]
Sorry for all the comments. It seems to be special character, but no errors are in the logs. hasnât signed Referrerâs agreement) but seems to be a good contact â

**Comment by D-McGovern** [comment]
I ran into this as well, wound up exporting to a spreadsheet and using regex to pare it down into what I needed to retain and know will process. This worked well for me:
=ArrayFormula(REGEXREPLACE(A1:A, "[^a-zA-Z0-9 /@$.-]+", ""))

**Comment by douglascayers** [comment]
@danhowellnz @D-McGovern Yes, this is the single most frustrating part about notes migration is that Salesforce does not provide any meaningful error messages when the creation of ContentNote fails due to invalid characters.

Thanks for the regex on replacing special characters.

I'm going to go ahead and close this issue as it sounds like the problem was invalid characters, which you identified and replaced.

**Comment by douglascayers** [comment]
I have future plans to try and detect such scenarios. If I get it working it will be covered by https://github.com/DouglasCAyers/sfdc-convert-notes-to-chatter-notes/issues/24
