### ISSUE TITLE
Weird behavior on migrating notes

### ISSUE THREAD

**Issue by markotomictoma** [DouglasCAyers/sfdc-convert-notes-to-chatter-notes#32]
I have just installed the app and triggered the Notes conversion. There are two things that are not clear to me:
1. I have 709 Notes in my Org and upon submitting the conversion in setup=>monitoring=>apex jobs I see 709 batches but it only gets to 592 and there stops. Status is processing but it never progress from 592. Am I missing something?
2. This one is realy weird. After I submitted the conversion and Job comes to 592 processed batches, I can see the new Notes in the Notes Related List. If I enter them I can clearly see it is the new one. However, I still don't have any ContentNote in the Org. select count() from contentnote returns 0. Contentnote is the new Note, right? 

Thank you in advance
Marko

**Comment by douglascayers** [comment]
Hi @markotomictoma,

Thanks for taking interest in my notes conversion tool =)

Regarding your questions,

1. I am not sure why the batch process is hanging. This may be due to waiting on system resources. You may abort the job in Setup menu and re-run the conversion job. Already converted records will not be processed again, they will intelligently be skipped.

2. Querying for ContentNote and ContentVersion abides by strange sharing rules that is unlike sharing on any other sobject I've encountered. To get results, you need to indirectly query them via the ContentDocumentLink object. Please see [this article](https://douglascayers.com/2017/06/26/how-to-export-notes-from-salesforce/) for more details.

Thanks,

Doug
