### ISSUE TITLE
I want to track notes conversion in a large org.

### ISSUE THREAD

**Issue by pmurillov** [DouglasCAyers/sfdc-convert-notes-to-chatter-notes#33]
Hello!

We are trying to convert classic notes to enhanced notes using your plug in. Which initially worked awesome. But now I am experiencing some issues and I was wonder if you could please help me with that:
Is there a way to track which records have been converted?
We have 2 million notes to be converted. We have been running the tool for several days now (because of SFDC limits) At the beginning we could see the progress (number of batches processed in apex jobs) but now it just stops (and after several hours of inactivity, I get an error: Salesforce System Error: 1956974305-450 (123133497) (123133497))
Also, is there a way to query converted notes? If I open parent records in the UI, I can see the new notes, but if I query ContentNote, I cannot see them. 

Any thoughts?
Thanks in advance,
Pam

**Comment by douglascayers** [comment]
Hi @pmurillov,

Wow, 2 million is a lot!

Regarding the Salesforce System Error, this vague message means that at least one of the Notes trying to be converted contains invalid characters not supported in ContentNote object. Unfortunately, the reported error will not tell you which record or what character(s) are problematic. [See here for some ways people have approached this](https://github.com/DouglasCAyers/sfdc-convert-notes-to-chatter-notes#salesforce-system-errors).

To track which records have been converted, you can query the custom object `Content_Notes_to_ContentNotes_Log__c`. It has fields for the old and new note ids. 

To query **ContentNote** or **ContentVersion** objects regardless of their conversion, you must go through the **ContentDocumentLink** object because of special sharing mechanisms around content. Please see [this article](https://douglascayers.com/2017/06/26/how-to-export-notes-from-salesforce/) about the sharing model and how to query them.

Good luck!

Doug

**Comment by pmurillov** [comment]
Thank you very much!!

2018-05-02 20:24 GMT-06:00 Doug Ayers <notifications@github.com>:
